##write rmarkdown HTMLs
rmarkdown::render("R/rmds/TCGA_BRCA.DSS.Rmd", output_file = "../../output/plots/mds/TCGA_BRCA.DSS.md")
rmarkdown::render("R/rmds/TCGA_BRCA.PFI.Rmd", output_file = "../../output/plots/mds/TCGA_BRCA.PFI.md")
rmarkdown::render("R/rmds/TCGA_COAD.DSS.Rmd", output_file = "../../output/plots/mds/TCGA_COAD.DSS.md")
rmarkdown::render("R/rmds/TCGA_COAD.PFI.Rmd", output_file = "../../output/plots/mds/TCGA_COAD.PFI.md")
rmarkdown::render("R/rmds/TCGA_LUAD.DSS.Rmd", output_file = "../../output/plots/mds/TCGA_LUAD.DSS.md")
rmarkdown::render("R/rmds/TCGA_LUAD.PFI.Rmd", output_file = "../../output/plots/mds/TCGA_LUAD.PFI.md")
rmarkdown::render("R/rmds/TCGA_OV.DSS.Rmd", output_file = "../../output/plots/mds/TCGA_OV.DSS.md")
rmarkdown::render("R/rmds/TCGA_OV.PFI.Rmd", output_file = "../../output/plots/mds/TCGA_OV.PFI.md")
rmarkdown::render("R/rmds/TCGA_UCEC.DSS.Rmd", output_file = "../../output/plots/mds/TCGA_UCEC.DSS.md")
rmarkdown::render("R/rmds/TCGA_UCEC.PFI.Rmd", output_file = "../../output/plots/mds/TCGA_UCEC.PFI.md")
